from django.db import models

# Create your models here.

class Discount(models.Model):
    """
    Represents a discount in the database.

    Attributes:
        code (str): The unique discount code.
        percentage (float): The discount percentage.
        expiration_date (datetime): The date and time the discount expires.
        created_at (datetime): The date and time the discount was created.
        revenue (float): The revenue generated by this discount.

    Returns:
        str: A string representation of the discount.
    """
    code = models.CharField(max_length=20, unique=True)
    percentage = models.DecimalField(max_digits=5, decimal_places=2)
    expiration_date = models.DateTimeField()
    created_at = models.DateTimeField(auto_now_add=True)
    revenue = models.DecimalField(max_digits=10, decimal_places=2)
    
    def __str__(self):
        return self.code