# Generated by Django 5.1.2 on 2025-01-20 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20250120_2314'),
    ]

    operations = [
    ]
