# Generated by Django 5.1.2 on 2025-01-10 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_tag_product_color_product_size_product_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product',
            new_name='name',
        ),
    ]
